
#pageHelper:
#  count: 200
#  soncount: 20
#eureka:
#  client:
#    serviceUrl: #\u6CE8\u518C\u4E2D\u5FC3\u7684\u6CE8\u518C\u5730\u5740
#      defaultZone: http://127.0.0.1:8080/eureka/
server:
  port: 8083
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/websocket?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    username: root
#    password: 1124
#    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: SERVICE
#  redis:
#    password: 1124
#    port: 6379
#    host: 127.0.0.1
    #\u670D\u52A1\u540D\u79F0--\u8C03\u7528\u7684\u65F6\u5019\u6839\u636E\u540D\u79F0\u6765\u8C03\u7528\u8BE5\u670D\u52A1\u7684\u65B9\u6CD5
#eureka.instance.lease-renewal-interval-in-seconds=10
#eureka.instance.lease-expiration-duration-in-seconds=30
#logging:
#  level:
#    com:
#      item:
#        mapper: debug
#  file:
#    path: spring
